
name: 'customer360'
version: '1.0.0'
config-version: 2

profile: 'customer360'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

models:
  customer360:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +materialized: table

seeds:
    +enabled: true
    +schema: "{% if target.name == 'local' %}seeds{% else %}{{ target.schema }}{% endif %}"

tests:
  +store_failures: true
  +schema: test